logging:
  file:
    name: ./logs/application.log
#  level:
#    org.springframework:
#      security: debug
vaadin:
  launch-browser: true
  frontend:
    hotdeploy: true
    allowed-packages: ru/menshevva/demoapp/ui

spring:
  application:
    name: demo-app
  profiles:
    group:
      local-dev:
        - db
        - report
      dev:
        - oauth
        - db
        - report
      test:
        - oauth
        - db
        - report
      prod:
        - oauth
        - db
        - report
server:
  port: ${PORT:8080}
