spring:
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  jpa:
    hibernate:
     ddl-auto: none

second:
  datasource:
#    enable: false
    url: ${SECOND_DB_URL}
    username: ${SECOND_DB_USER}
    password: ${SECOND_DB_PASSWORD}
    configuration: